# Generated by Django 4.2.7 on 2023-11-29 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=200, verbose_name="Название предмета"),
                ),
                (
                    "description",
                    models.TextField(max_length=200, verbose_name="описание предмета"),
                ),
                (
                    "price",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Количество ингредиентов",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Количество",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предмет",
            },
        ),
    ]
