version: '3.10'

services:
  app:
    build: .
    restart: always
    volumes:
      - static_value:/app/StripeApp/static/
      - media_value:/app/StripeApp/media/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static:ro
      - media_value:/var/html/
    depends_on:
      - app

volumes:
  static_value:
  media_value:
 # db_data: